---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  ssh_key: <%= ENV['HOME'] %>/.ssh/<%= ENV['AWS_SSH_KEY'] %>.pem
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  flavor_id: c3.xlarge
  username: ubuntu

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cwtest::default]
    attributes:
